<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="zh-CN" lang="zh-CN" >
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="房角石注释丛书">
  <meta name="keywords" content="房角石注释丛书">
  <title>救恩的本质就是认识雅威-出埃及记-房角石圣经注释丛书</title>
  <link rel="https://ehome.endao.co/book_image/detail/1670316623378.png">
  <link rel="stylesheet" href="../assets/css/style.css">

</head>
<body>
  <div class="content-wrapper">
    <?php include "../header.html" ?>
    <div class="container">
      <div class="row py-16">
        <div class="col-xl-6 col-md-10 col-lg-6 order-xl-2 mx-auto">
          <!-- 内容开始 -->

          
<section style="font-size: 15px; color: rgb(0, 0, 0); letter-spacing: 0.4px; line-height: 1.8; padding: 0px 12px; box-sizing: border-box;   text-align: justify;"><section style="margin: 10px 0px; text-align: left; justify-content: flex-start; display: flex; flex-flow: row nowrap; position: static; box-sizing: border-box;" class="_135editor"><section style="box-sizing:border-box;display: inline-block; vertical-align: bottom; width: auto; min-width: 10%; max-width: 100%; flex: 0 0 auto; height: auto; align-self: flex-end; margin: 0px -20px 0px 0px;"><section style="text-align: center; margin: 0px; position: static; box-sizing: border-box;"><section class="group-empty" style="box-sizing:border-box;display: inline-block; width: 47px; height: 47px; vertical-align: top; overflow: hidden; border-width: 0px; border-radius: 77px; border-style: solid; border-color: rgb(62, 62, 62); background-image: linear-gradient(to top, rgb(255, 243, 173) 0%, rgba(255, 243, 173, 0) 100%);"><svg viewbox="0 0 1 1" style="box-sizing:border-box;float:left;line-height:0;width:0;vertical-align:top;"></svg></section></section></section><section style="box-sizing:border-box;display: inline-block; vertical-align: bottom; width: auto; min-width: 10%; max-width: 100%; flex: 0 0 auto; height: auto; align-self: flex-end;"><section style="text-align: center; box-sizing: border-box;"><p style="margin: 0px; padding: 0px; box-sizing: border-box;"><strong style="box-sizing: border-box;">书 &nbsp; 卷 &nbsp; 导 &nbsp; 读 ✦</strong>
				</p></section><section style="margin: 0px; position: static; box-sizing: border-box;"><section style="font-size: 13px; text-align: justify; box-sizing: border-box;"><p style="text-align:left;  margin: 0px; padding: 0px; box-sizing: border-box;"><span style="background-color: #3E3E3E; color: #FFFFFF; box-sizing: border-box;">Books Introduction</span>
					</p></section></section></section></section><section style="text-align: center; font-size: 24px; box-sizing: border-box;" class="_135editor"><p style="margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p><p style="margin: 0px; padding: 0px; box-sizing: border-box;"><strong style="box-sizing: border-box;">救恩的本质就是认识雅威</strong>
		</p><p style="margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p></section><section style="text-align: center; justify-content: center; display: flex; flex-flow: row nowrap; margin: 10px 0px; position: static; box-sizing: border-box;transform: translate3d(9px, 0px, 0px);-webkit-transform: translate3d(9px, 0px, 0px);-moz-transform: translate3d(9px, 0px, 0px);-o-transform: translate3d(9px, 0px, 0px);" class="_135editor"><section style="box-sizing:border-box;display: inline-block; vertical-align: bottom; width: 105px; align-self: flex-end; flex: 0 0 auto; height: auto;"><section style="text-align: left; justify-content: flex-start; display: flex; flex-flow: row nowrap; position: static; box-sizing: border-box;"><section style="box-sizing:border-box;max-width: 100% !important;display: inline-block; width: 100%; vertical-align: top; align-self: flex-start; flex: 0 0 auto; background-color: rgb(248, 208, 95); border-width: 0px; border-radius: 405%; border-style: none; border-color: rgb(62, 62, 62); overflow: hidden; height: auto; box-shadow: rgb(255, 255, 255) -25px 0px 27px inset;"><section style="text-align: justify; box-sizing: border-box;"><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
						</p></section><section style="text-align: center; position: static; box-sizing: border-box;"><section style="text-align: justify; box-sizing: border-box;"><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
							</p></section></section><section style="text-align: justify; box-sizing: border-box;"><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
						</p></section></section></section></section><section style="box-sizing:border-box;display: inline-block; vertical-align: middle; width: 52%; flex: 0 0 auto; height: auto; align-self: center;"><section style="margin-top: 10px; margin-bottom: 10px; line-height: 0; position: static; box-sizing: border-box;transform: translate3d(-56px, 0px, 0px);-webkit-transform: translate3d(-56px, 0px, 0px);-moz-transform: translate3d(-56px, 0px, 0px);-o-transform: translate3d(-56px, 0px, 0px);"><section style="box-sizing:border-box;max-width: 100%; vertical-align: middle; display: inline-block; line-height: 0; width: 80%; height: auto;"><img class="raw-image" style="box-sizing:border-box;vertical-align: middle; width: 100%;" _width="100%" src="https://img.xiumi.us/xmi/ua/3O1Ws/i/71a11486bd7b876bb1893c242cac2ce6-sz_319936.jpeg" draggable="false" _src="https://img.xiumi.us/xmi/ua/3O1Ws/i/71a11486bd7b876bb1893c242cac2ce6-sz_319936.jpeg"/>
				</section></section><section style="text-align: left; margin: 0px 0px 10px; position: static; box-sizing: border-box;transform: translate3d(-56px, 0px, 0px);-webkit-transform: translate3d(-56px, 0px, 0px);-moz-transform: translate3d(-56px, 0px, 0px);-o-transform: translate3d(-56px, 0px, 0px);"><section style="box-sizing: border-box;"><p style="margin: 0px; padding: 0px; box-sizing: border-box;"><span style="letter-spacing: 0.4px; box-sizing: border-box;">房角石圣经注释丛书</span><strong style="box-sizing: border-box;"><br style="box-sizing: border-box;"/></strong>
					</p><p style="margin: 0px; padding: 0px; box-sizing: border-box;"><strong style="box-sizing: border-box;"><span style="letter-spacing: 0.4px; box-sizing: border-box;">第一卷下：出埃及记</span></strong>
					</p></section></section></section></section><section style="padding: 0px 12px; letter-spacing: 0.4px; line-height: 1.9; font-size: 16px; box-sizing: border-box;" class="_135editor"><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="box-sizing: border-box;"><br style="box-sizing: border-box;"/></span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="box-sizing: border-box;">神是谁？</span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="box-sizing: border-box;">他如何解决人类的困境？</span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="box-sizing: border-box;">他救恩的本质是什么？</span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="box-sizing: border-box;"><br style="box-sizing: border-box;"/></span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="box-sizing: border-box;"><span style="color: #000000; box-sizing: border-box;">若要对这些问题寻根溯源，我们必须阅读出埃及记，这卷书是认识圣经核心信息的基础，因为“圣经所理解的那种</span><span style="color: #FF8124; box-sizing: border-box;">赐予生命的神人关系</span><span style="color: #000000; box-sizing: border-box;">是在出埃及记里逐渐定型的”</span><span style="color: #FFCA00; box-sizing: border-box;">[1]</span><span style="font-size: 15px; box-sizing: border-box;">。</span><span style="color: #000000; box-sizing: border-box;">出埃及记将神的启示渐次展开，讲述了拯救和立约的故事，与新约中逐渐显明的救赎计划遥相呼应，令人赞叹、敬畏。</span></span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="box-sizing: border-box;"><br style="box-sizing: border-box;"/></span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="box-sizing: border-box;"><span style="color: #000000; box-sizing: border-box;">约翰·奥斯华博士在</span><span style="color: #FF8124; box-sizing: border-box;">《房角石注释：出埃及记》</span><span style="color: #000000; box-sizing: border-box;">中将这卷书蕴含的真理娓娓道来，让我们更深地认识神的本质和救恩的意义。</span></span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="box-sizing: border-box;"><br style="box-sizing: border-box;"/></span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="box-sizing: border-box;"><span style="color: #000000; box-sizing: border-box;">“宇宙中只有一种存在是‘他者’，有别于这宇宙，那就是雅威。”</span><span style="color: #FFCA00; box-sizing: border-box;">[2]</span><span style="color: #000000; box-sizing: border-box;">奥斯华博士在导言中介绍了古近东的宗教背景，使我们看到雅威的自我启示如何与以色列人所处的历史时空息息相关。他认为，雅威正是通过对抗埃及的假神，又赐下圣约，来彰显他独一神圣的性情和本质。人类真正的问题就是离开了真神这生命的源头，从此被罪和死捆绑。拯救并非挪去后果，而是“让我们认识雅威才是我们生命中至关重要的实在”</span><span style="color: #FFCA00; box-sizing: border-box;">[3]</span><span style="font-size: 15px; box-sizing: border-box;">。</span></span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p></section><section style="margin: 0px 0%; text-align: left; justify-content: flex-start; display: flex; flex-flow: row nowrap; position: static; box-sizing: border-box;" class="_135editor"><section style="box-sizing:border-box;max-width: 100% !important;display: inline-block; width: 100%; vertical-align: top; padding: 20px; align-self: flex-start; flex: 0 0 auto; background-image: linear-gradient(to top, rgb(255, 243, 173) 0%, rgba(255, 243, 173, 0) 100%);"><section style="text-align: center; margin: 0px 0% 20px; line-height: 0; position: static; box-sizing: border-box;"><section style="box-sizing:border-box;max-width: 100%; vertical-align: middle; display: inline-block; line-height: 0; width: 60%; height: auto;"><img class="raw-image" style="box-sizing:border-box;vertical-align: middle; width: 100%;" _width="100%" src="https://ehome.endao.co/book_image/detail/1669887987892.png" draggable="false" _src="https://ehome.endao.co/book_image/detail/1669887987892.png"/>
				</section></section><section style="color: rgb(0, 0, 0); text-align: justify; font-size: 16px; letter-spacing: 0.4px; line-height: 1.9; padding: 0px 12px; box-sizing: border-box;"><p style="text-align:center;  margin: 0px; padding: 0px; box-sizing: border-box;"><strong style="box-sizing: border-box;">✦ &nbsp;房角石</strong><strong style="letter-spacing: 0.4px; box-sizing: border-box;">圣经注释丛书&nbsp; ✦</strong>
				</p><p style="text-align:center;  margin: 0px; padding: 0px; box-sizing: border-box;"><strong style="box-sizing: border-box;"><span style="background-color: #FFCA00; color: #FFFFFF; box-sizing: border-box;">全套34册 | 简体/繁體</span></strong>
				</p><p style="text-align:center;  margin: 0px; padding: 0px; box-sizing: border-box;"><span style="text-decoration: none; color: #000000; box-sizing: border-box;">人人都能读的高品质释经书</span>
				</p><p style="text-align:center;  margin: 0px; padding: 0px; box-sizing: border-box;"><a href="https://cbcs.endao.co/" target="_blank" style="color: rgb(255, 129, 36); box-sizing: border-box;" _href="https://cbcs.endao.co/"><span style="color: #FF8124; box-sizing: border-box;">点击了解更多→&nbsp;cbcs.endao.co</span></a>
				</p></section></section></section><section style="padding: 0px 12px; letter-spacing: 0.4px; line-height: 1.8; font-size: 16px; box-sizing: border-box;" class="_135editor"><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p></section><section style="display: flex; flex-flow: row nowrap; margin: 10px 0%; text-align: center; justify-content: center; position: static; box-sizing: border-box;" class="_135editor"><section style="box-sizing:border-box;display: inline-block; vertical-align: middle; width: auto; flex: 0 0 0%; align-self: center; height: auto; margin: 0px; padding: 0px; box-shadow: rgb(0, 0, 0) 0px 0px 0px;"><section style="display: flex; flex-flow: row nowrap; justify-content: center; margin: -1px 0% 5px; position: static; box-sizing: border-box;"><section style="box-sizing:border-box;display: inline-block; vertical-align: bottom; width: auto; align-self: flex-end; flex: 0 0 0%; line-height: 0; letter-spacing: 0px; height: auto;"><section style="margin: 8px 0% -5px; position: static; box-sizing: border-box;transform: translate3d(1px, 0px, 0px);-webkit-transform: translate3d(1px, 0px, 0px);-moz-transform: translate3d(1px, 0px, 0px);-o-transform: translate3d(1px, 0px, 0px);"><section class="group-empty" style="box-sizing:border-box;display: inline-block; width: 6px; height: 6px; vertical-align: top; overflow: hidden; border-style: solid; border-width: 1px; border-radius: 50px 0px 50px 50px; border-color: rgb(255, 197, 41);"><svg viewbox="0 0 1 1" style="box-sizing:border-box;float:left;line-height:0;width:0;vertical-align:top;"></svg></section></section></section><section class="group-empty" style="box-sizing:border-box;display: inline-block; vertical-align: top; width: 22px; flex: 0 0 auto; align-self: stretch; height: auto; border-style: none none solid solid; border-width: 1px;  border-color: rgb(62, 62, 62) rgb(62, 62, 62) rgb(255, 197, 41) rgb(255, 197, 41);"><svg viewbox="0 0 1 1" style="box-sizing:border-box;float:left;line-height:0;width:0;vertical-align:top;"></svg></section></section></section><section style="box-sizing:border-box;display: inline-block; vertical-align: middle; width: auto; align-self: center; flex: 100 100 0%;"><section style="margin: 2px 0% 0px; position: static; box-sizing: border-box;"><section style="background-color: rgb(255, 197, 41); height: 1px; box-sizing: border-box;"><svg viewbox="0 0 1 1" style="box-sizing:border-box;float:left;line-height:0;width:0;vertical-align:top;"></svg></section></section></section></section><section style="padding: 0px 12px; font-size: 16px; box-sizing: border-box;" class="_135editor"><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="font-size: 12px; color: #3E3E3E; box-sizing: border-box;">[1]&nbsp;约翰·奥斯华，《房角石圣经注释丛书第一卷下：出埃及记》，侯春彦译（香港：恩道出版社，2019），27。</span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="font-size: 12px; color: #3E3E3E; box-sizing: border-box;">[2]&nbsp;奥斯华，《房角石圣经注释丛书第一卷下：出埃及记》，47。</span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="font-size: 12px; color: #3E3E3E; box-sizing: border-box;">[3]&nbsp;奥斯华，《房角石圣经注释丛书第一卷下：出埃及记》，40。</span>
		</p></section></section>
          
          <!-- 内容结束 -->
        </div>
      </div>
    </div>
  </div>
  <?php include "../footer.html" ?>
  <div class="progress-wrap">
    <svg class="progress-circle svg-content" width="100%" height="100%" viewBox="-1 -1 102 102">
      <path d="M50,1 a49,49 0 0,1 0,98 a49,49 0 0,1 0,-98" />
    </svg>
  </div>
</body>

</html>