<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="zh-CN" lang="zh-CN" >
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="房角石圣经注释丛书">
  <meta name="keywords" content="房角石圣经注释丛书">
  <title>雅威是独一神圣的「他者」-出埃及记-房角石圣经注释丛书</title>
  <link rel="shortcut icon" href="../assets/img/favicon.png">
  <link rel="stylesheet" href="../assets/css/styles.css">

</head>
<body>
  <div class="content-wrapper">
    <?php include "../header.html" ?>
    <div class="container">
      <div class="row py-16">
        <div class="col-xl-6 col-md-10 col-lg-6 order-xl-2 mx-auto">
          <!-- 内容开始 -->

          <section style="font-size: 15px; color: rgb(0, 0, 0); letter-spacing: 0.4px; line-height: 1.8; padding: 0px 12px; box-sizing: border-box;   text-align: justify;"><section style="margin: 10px 0px; text-align: left; justify-content: flex-start; display: flex; flex-flow: row nowrap; position: static; box-sizing: border-box;" class="_135editor"><section style="box-sizing:border-box;display: inline-block; vertical-align: bottom; width: auto; min-width: 10%; max-width: 100%; flex: 0 0 auto; height: auto; align-self: flex-end; margin: 0px -20px 0px 0px;"><section style="text-align: center; margin: 0px; position: static; box-sizing: border-box;"><section class="group-empty" style="box-sizing:border-box;display: inline-block; width: 47px; height: 47px; vertical-align: top; overflow: hidden; border-width: 0px; border-radius: 77px; border-style: solid; border-color: rgb(62, 62, 62); background-image: linear-gradient(to top, rgb(255, 243, 173) 0%, rgba(255, 243, 173, 0) 100%);"><svg viewbox="0 0 1 1" style="box-sizing:border-box;float:left;line-height:0;width:0;vertical-align:top;"></svg></section></section></section><section style="box-sizing:border-box;display: inline-block; vertical-align: bottom; width: auto; min-width: 10%; max-width: 100%; flex: 0 0 auto; height: auto; align-self: flex-end;"><section style="text-align: center; box-sizing: border-box;"><p style="margin: 0px; padding: 0px; box-sizing: border-box;"><strong style="box-sizing: border-box;">编 &nbsp;辑 &nbsp;分 &nbsp;享 ✦</strong>
				</p></section><section style="margin: 0px; position: static; box-sizing: border-box;"><section style="font-size: 13px; text-align: justify; box-sizing: border-box;"><p style="text-align:left;  margin: 0px; padding: 0px; box-sizing: border-box;"><span style="background-color: #3E3E3E; color: #FFFFFF; box-sizing: border-box;">&nbsp;Editor‘s Sharing&nbsp;</span>
					</p></section></section></section></section><section style="text-align: center; font-size: 24px; box-sizing: border-box;" class="_135editor"><p style="margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p><p style="margin: 0px; padding: 0px; box-sizing: border-box;"><strong style="box-sizing: border-box;"><span style="color: #000000; box-sizing: border-box;">雅威是独一神圣的「他者」</span></strong>
		</p><p style="margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p></section><section style="margin: 0px 0%; text-align: left; justify-content: flex-start; display: flex; flex-flow: row nowrap; position: static; box-sizing: border-box;" class="_135editor"><section style="box-sizing:border-box;max-width: 100% !important;display: inline-block; width: 100%; vertical-align: top; padding: 20px; align-self: flex-start; flex: 0 0 auto; background-image: linear-gradient(to top, rgb(255, 243, 173) 0%, rgba(255, 243, 173, 0) 100%);"><section style="text-align: center; margin: 0px 0% 20px; line-height: 0; position: static; box-sizing: border-box;"><section style="box-sizing:border-box;max-width: 100%; vertical-align: middle; display: inline-block; line-height: 0; width: 90%; height: auto;"><img class="raw-image" style="box-sizing:border-box;vertical-align: middle; width: 100%;" _width="100%" src="https://ehome.endao.co/book_image/detail/1670320805724.jpg" draggable="false" _src="https://img.xiumi.us/xmi/ua/3O1Ws/i/614f6c8bd4c9c89de85f7093191c3066-sz_156818.jpg"/>
				</section></section><section style="color: rgb(0, 0, 0); text-align: justify; letter-spacing: 0.4px; line-height: 1.8; padding: 0px 12px; box-sizing: border-box;"><p style=" margin: 0px; padding: 0px; box-sizing: border-box;">“神的圣洁”为何成为出埃及记的重要主题？神如何渐进地启示自己？救恩的意义是什么？奥斯华博士的阐释为我们揭开了问题的答案。</p></section></section></section><section style="letter-spacing: 0.4px; line-height: 1.8; padding: 0px 12px; font-size: 16px; box-sizing: border-box;" class="_135editor"><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p><p style="text-align:right;  margin: 0px; padding: 0px; box-sizing: border-box;"><span style="color: #000000; box-sizing: border-box;"><strong style="box-sizing: border-box;"><span style="color: #000000; box-sizing: border-box;">文</span></strong><span style="color: #000000; box-sizing: border-box;"> | 艾希</span></span>
		</p><p style="text-align:right;  margin: 0px; padding: 0px; box-sizing: border-box;"><span style="color: #000000; box-sizing: border-box;"><span style="font-size: 15px; box-sizing: border-box;"><br style="box-sizing: border-box;"/></span></span>
		</p><p style="text-align:right;  margin: 0px; padding: 0px; box-sizing: border-box;"><span style="color: #000000; box-sizing: border-box;"><span style="font-size: 15px; box-sizing: border-box;"><br style="box-sizing: border-box;"/></span></span>
		</p></section><section style="padding: 0px 12px; letter-spacing: 0.4px; line-height: 1.9; font-size: 16px; color: rgb(0, 0, 0); box-sizing: border-box;" class="_135editor"><p style="text-align:center;  margin: 0px; padding: 0px; box-sizing: border-box;"><span style="box-sizing: border-box;"><strong style="box-sizing: border-box;"><span style="color: #000000; box-sizing: border-box;">“你们将谁比我，叫他与我相等呢？”</span></strong></span>
		</p><p style="text-align:center;  margin: 0px; padding: 0px; box-sizing: border-box;"><span style="color: #000000; box-sizing: border-box;">以赛亚书40:25</span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="font-size: 15px; color: #000000; box-sizing: border-box;">&nbsp;</span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="color: #000000; box-sizing: border-box;">“圣洁”一词在今天的神学和教会情境下司空见惯，但实际上，该词的词根<span style="color: #FF8124; box-sizing: border-box;"><em style="box-sizing: border-box;">qadash</em></span>在创世记中只出现了4次，并且没有一次用作表明神的本质（3次用于指“庙妓”，1次用于指圣安息日），但是，到了出埃及记，它以各种形式出现了100次之多，后来在旧约别处又出现了700次以上，成为一个常用词。<span style="color: #FFCA00; box-sizing: border-box;">[1]</span>我们如何理解这一鲜明的对比呢？</span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="font-size: 15px; color: #000000; box-sizing: border-box;"><br style="box-sizing: border-box;"/></span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="color: #000000; box-sizing: border-box;">约翰·奥斯华博士在<span style="color: #FF8124; box-sizing: border-box;">《房角石注释：出埃及记》</span>的导言中指出，“神的圣洁”乃出埃及记的重要神学主题之一，本文尝试简述作者的解经脉络，探寻神如何逐步启示了他圣洁的本质。</span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="font-size: 15px; color: #000000; box-sizing: border-box;"><br style="box-sizing: border-box;"/></span>
		</p></section><section style="text-align: left; justify-content: flex-start; display: flex; flex-flow: row nowrap; margin: 10px 0px; position: static; box-sizing: border-box;" class="_135editor"><section style="box-sizing:border-box;display: inline-block; vertical-align: middle; width: auto; align-self: center; flex: 0 0 auto; min-width: 5%; max-width: 100%; height: auto; padding: 0px; margin: 0px 10px 0px 0px;"><section style="text-align: center; margin: 0px; position: static; box-sizing: border-box;"><section style="box-sizing:border-box;display: inline-block; width: 47px; height: 47px; vertical-align: top; overflow: hidden; border-width: 0px; border-radius: 410px; border-style: none; border-color: rgb(62, 62, 62); background-color: rgb(248, 208, 95); box-shadow: rgb(255, 255, 255) -11px -7px 25px inset;"><section style="text-align: justify; font-size: 26px; box-sizing: border-box;"><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
						</p></section></section></section></section><section style="box-sizing:border-box;display: inline-block; vertical-align: middle; width: auto; align-self: center; flex: 0 0 auto; min-width: 5%; max-width: 100%; height: auto; padding: 0px;"><section style="text-align: justify; font-size: 23px; color: rgb(0, 0, 0); box-sizing: border-box;"><p style=" margin: 0px; padding: 0px; box-sizing: border-box;">异教背景</p></section></section><section class="group-empty" style="box-sizing:border-box;display: inline-block; vertical-align: top; width: auto; min-width: 5%; max-width: 100%; flex: 0 0 auto; height: auto; margin: 0px 0px 0px 15px;"><svg viewbox="0 0 1 1" style="box-sizing:border-box;float:left;line-height:0;width:0;vertical-align:top;"></svg></section></section><section style="padding: 0px 12px; letter-spacing: 0.4px; line-height: 1.9; font-size: 16px; box-sizing: border-box;" class="_135editor"><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="font-size: 15px; color: #000000; box-sizing: border-box;"><br style="box-sizing: border-box;"/></span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="color: #000000; box-sizing: border-box;">我们知道，神进入了以色列人的历史，成为这个民族历史叙事中的主角，在此过程中他渐进地启示自己，这启示首先是面向身处异教世界的以色列人，与他们置身其中的信仰背景息息相关。</span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="color: #000000; box-sizing: border-box;"><br style="box-sizing: border-box;"/></span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="color: #000000; box-sizing: border-box;">奥斯华博士告诉我们，在古近东的异教文化中，人们认为宇宙中的一切彼此密切关联，人、神明、自然界之间没有分别，任一领域发生的事，都会影响另外两个领域。这种观念的表现形式就是<span style="color: #FF8124; box-sizing: border-box;">偶像崇拜</span>，人们用可见的形象代表不可见的神祇，通过对偶像施加影响，来影响其背后的力量。<span style="color: #FF8124; box-sizing: border-box;"><em style="box-sizing: border-box;">Qadash</em></span>在当时仅用作描述与神明有关的事物，并不包含道德意义。诸神皆为圣，无论是生命之神，还是死亡之神，洁净之神，还是瘟疫之神。</span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="color: #000000; box-sizing: border-box;"><br style="box-sizing: border-box;"/></span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="color: #000000; box-sizing: border-box;">在创世记，该词没有出现在神和以色列先祖接触、互动的过程中，因为神要避免使用被异教玷污的语汇，以免人将他与假神混为一谈。神采用的方式是与先祖建立个人的关系，显明他是可以信靠的，“这就好像神在对这些人说：‘忘记你们过去对神明的所有认识，只要来与我同行。’”<span style="color: #FFCA00; box-sizing: border-box;">[2]</span>。</span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="font-size: 15px; color: #000000; box-sizing: border-box;"><br style="box-sizing: border-box;"/></span>
		</p></section><section style="padding: 0px 12px; letter-spacing: 0.4px; line-height: 1.9; font-size: 16px; color: rgb(0, 0, 0); box-sizing: border-box;" class="_135editor"><p style=" margin: 0px; padding: 0px; box-sizing: border-box;">以色列人在埃及为奴400年，那里有着复杂的多神信仰体系，简言之，埃及人的宗教观念是：神有许多位，人能通过操纵世界来操纵神；神与性密切相关；神和世界没有区别，性情和人一样。<br style="box-sizing: border-box;"/>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p></section><section style="text-align: left; justify-content: flex-start; display: flex; flex-flow: row nowrap; margin: 10px 0px; position: static; box-sizing: border-box;" class="_135editor"><section style="box-sizing:border-box;display: inline-block; vertical-align: middle; width: auto; align-self: center; flex: 0 0 auto; min-width: 5%; max-width: 100%; height: auto; padding: 0px; margin: 0px 10px 0px 0px;"><section style="text-align: center; margin: 0px; position: static; box-sizing: border-box;"><section style="box-sizing:border-box;display: inline-block; width: 47px; height: 47px; vertical-align: top; overflow: hidden; border-width: 0px; border-radius: 410px; border-style: none; border-color: rgb(62, 62, 62); background-color: rgb(248, 208, 95); box-shadow: rgb(255, 255, 255) -11px -7px 25px inset;"><section style="text-align: justify; font-size: 26px; box-sizing: border-box;"><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
						</p></section></section></section></section><section style="box-sizing:border-box;display: inline-block; vertical-align: middle; width: auto; align-self: center; flex: 0 0 auto; min-width: 5%; max-width: 100%; height: auto; padding: 0px;"><section style="text-align: justify; font-size: 23px; color: rgb(0, 0, 0); box-sizing: border-box;"><p style=" margin: 0px; padding: 0px; box-sizing: border-box;">神的启示</p></section></section><section class="group-empty" style="box-sizing:border-box;display: inline-block; vertical-align: top; width: auto; min-width: 5%; max-width: 100%; flex: 0 0 auto; height: auto; margin: 0px 0px 0px 15px;"><svg viewbox="0 0 1 1" style="box-sizing:border-box;float:left;line-height:0;width:0;vertical-align:top;"></svg></section></section><section style="padding: 0px 12px; letter-spacing: 0.4px; line-height: 1.9; font-size: 16px; box-sizing: border-box;" class="_135editor"><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="font-size: 15px; color: #000000; box-sizing: border-box;"><br style="box-sizing: border-box;"/></span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="color: #000000; box-sizing: border-box;">雅威在荆棘中显现，呼召摩西带领以色列人离开埃及，那时他如何表明自己的身份呢？他强调说，<span style="color: #FF8124; box-sizing: border-box;">他是以色列人先祖的神</span>（出3:6）。亚伯拉罕、以撒、雅各，他们每一位都曾与神同行。以色列人已经从本民族的口传故事中，听说了这位向先祖显现的神，知道他是可以信靠的。</span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="color: #000000; box-sizing: border-box;"><br style="box-sizing: border-box;"/></span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="color: #000000; box-sizing: border-box;">现在，神要借着出埃及的拯救和西奈山的立约进一步自我启示，出埃及记的故事回答了这样三个萦绕人心的重要问题：</span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="color: #000000; box-sizing: border-box;">&nbsp;</span>
		</p><section class="_135editor" data-role="list"><ul class="list-paddingleft-2" style="list-style-type: disc;"><li><p style="margin: 0px; padding: 0px; box-sizing: border-box;"><span style="color: #000000; box-sizing: border-box;">神是超越、独一的主宰吗？</span></p></li><li><p style="margin: 0px; padding: 0px; box-sizing: border-box;"><span style="color: #000000; box-sizing: border-box;">神关心人类的需要吗？</span></p></li><li><p style="margin: 0px; padding: 0px; box-sizing: border-box;"><span style="color: #000000; box-sizing: border-box;">神的本质、性情如何？</span></p></li></ul></section><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="color: #000000; box-sizing: border-box;">&nbsp;</span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="color: #000000; box-sizing: border-box;">在埃及，神降下十灾，攻击埃及的假神，粉碎了百姓对神错误的认识，让他们明白雅威才是独一的真神。在旷野，神供应食物和水，又使他们在争战中得胜，让百姓知道<span style="color: #FF8124; box-sizing: border-box;">这位神不仅大有能力，而且关心人的需要。</span></span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="color: #000000; box-sizing: border-box;"><br style="box-sizing: border-box;"/></span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="color: #000000; box-sizing: border-box;">那么，神的性情和本质如何呢？他与人、与世界有分别吗？</span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="color: #000000; box-sizing: border-box;"><br style="box-sizing: border-box;"/></span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="color: #000000; box-sizing: border-box;">在燃烧的荆棘中，这个问题的答案已昭然若揭。那时，摩西想要近前观看荆棘中火焰的异象，却被要求脱下脚上的鞋，因为他所站之地是圣地。“这番话绝不可能是随口说的。如果神真是良善可靠、可以接近的，那么他也确实与我们<span style="color: #FF8124; box-sizing: border-box;">截然有别</span>。”<span style="color: #FFCA00; box-sizing: border-box;">[3]</span>。奥斯华博士解释说，独一的真神显现在荆棘中，摩西鞋底的普通尘土和荆棘周围的尘土就有了本质上的区别，所以两者不能相混。</span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="color: #000000; box-sizing: border-box;"><br style="box-sizing: border-box;"/></span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="color: #000000; box-sizing: border-box;">以色列人离开埃及，经过旷野，终于来到圣山脚下，在这座山上，神要向百姓亲自显现，借着立约更深刻、更完全地启示他自己。神的圣洁，在立约的背景下才初次清晰地启示出来，成为出埃及记乃至整本圣经重要的神学主题。这是因为，神要使用<span style="color: #FF8124; box-sizing: border-box;">圣约</span>的形式，通过他的律例典章，让百姓认识立约之主的性情，显明他与诸神的分别，这样百姓就不会误解圣洁的真正内涵。</span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="color: #000000; box-sizing: border-box;"><br style="box-sizing: border-box;"/></span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="color: #000000; box-sizing: border-box;">百姓需要自洁，才能领受圣约，神借着自洁的要求表明他圣洁的本质：洗衣服、在山四围定界限、禁戒性行为（出19:10－15）。这些规定具有象征意义，<span style="color: #FF8124; box-sizing: border-box;">神要打破百姓从埃及承继的宗教观念，显明他真正的本质</span>。</span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="color: #000000; box-sizing: border-box;"><br style="box-sizing: border-box;"/></span>
		</p><section class="_135editor" data-role="list"><ul class="list-paddingleft-2" style="list-style-type: disc;"><li><p style="margin: 0px; padding: 0px; box-sizing: border-box;"><span style="color: #000000; box-sizing: border-box;">神全然洁净，毫无污秽，所以来到他的面前，必须穿洁净的衣服；</span></p></li><li><p style="margin: 0px; padding: 0px; box-sizing: border-box;"><span style="color: #000000; box-sizing: border-box;">神不是世界，他与受造物之间有绝对的界限，人无法靠近神，所以要在山的四围划定界限，越过者必须处死；</span></p></li><li><p style="margin: 0px; padding: 0px; box-sizing: border-box;"><span style="color: #000000; box-sizing: border-box;">最后，性行为本身并非坏事，但人无法借由性行为影响神，他超越一切，也超越了性。<span style="color: #FFCA00; box-sizing: border-box;">[4]</span></span></p></li></ul></section></section><section style="padding: 0px 12px; letter-spacing: 0.4px; line-height: 1.9; font-size: 16px; box-sizing: border-box;" class="_135editor"><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="font-size: 15px; color: #000000; box-sizing: border-box;"><br style="box-sizing: border-box;"/></span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="color: #000000; box-sizing: border-box;">“宇宙中只有一种存在是‘他者’，有别于这宇宙，那就是雅威”<span style="color: #FFCA00; box-sizing: border-box;">[5]</span>。</span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="color: #000000; box-sizing: border-box;"><br style="box-sizing: border-box;"/></span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="color: #000000; box-sizing: border-box;">伟大的出埃及之旅，应许之地并非终点。神一步一步启示自己，是为了让以色列百姓，以及今天的我们认识他是谁，他与我们之间有何等判若天渊的距离，我们如何按照他的方式跨越这距离，与他建立至关重要的关系。</span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="color: #000000; box-sizing: border-box;"><br style="box-sizing: border-box;"/></span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="color: #000000; box-sizing: border-box;">“如果人要活在与神的亲密相交中，就永不可无视或忽视神与我们完全不同这一事实。不仅如此，而且要由神（而非我们）来决定我们如何活在他圣洁的同在中。”<span style="color: #FFCA00; box-sizing: border-box;">[6]</span>。</span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p></section><section style="margin: 0px 0%; text-align: left; justify-content: flex-start; display: flex; flex-flow: row nowrap; position: static; box-sizing: border-box;" class="_135editor"><section style="box-sizing:border-box;max-width: 100% !important;display: inline-block; width: 100%; vertical-align: top; padding: 20px; align-self: flex-start; flex: 0 0 auto; background-image: linear-gradient(to top, rgb(255, 243, 173) 0%, rgba(255, 243, 173, 0) 100%);"><section style="text-align: center; margin: 0px 0% 20px; line-height: 0; position: static; box-sizing: border-box;"><section style="box-sizing:border-box;max-width: 100%; vertical-align: middle; display: inline-block; line-height: 0; width: 60%; height: auto;"><img class="raw-image" style="box-sizing:border-box;vertical-align: middle; width: 100%;" _width="100%" src="https://ehome.endao.co/book_image/detail/1669887987892.png" draggable="false" _src="https://img.xiumi.us/xmi/ua/3O1Ws/i/06486484a6d3c53eb584ac03bbe449d9-sz_1979970.png"/>
				</section></section><section style="color: rgb(0, 0, 0); text-align: justify; font-size: 16px; letter-spacing: 0.4px; line-height: 1.9; padding: 0px 12px; box-sizing: border-box;"><p style="text-align:center;  margin: 0px; padding: 0px; box-sizing: border-box;"><strong style="box-sizing: border-box;">✦ &nbsp;房角石</strong><strong style="letter-spacing: 0.4px; box-sizing: border-box;">圣经注释丛书&nbsp; ✦</strong>
				</p><p style="text-align:center;  margin: 0px; padding: 0px; box-sizing: border-box;"><strong style="box-sizing: border-box;"><span style="background-color: #FFCA00; color: #FFFFFF; box-sizing: border-box;">全套34册 | 简体/繁體</span></strong>
				</p><p style="text-align:center;  margin: 0px; padding: 0px; box-sizing: border-box;"><span style="text-decoration: none; color: #000000; box-sizing: border-box;">人人都能读的高品质释经书</span>
				</p><p style="text-align:center;  margin: 0px; padding: 0px; box-sizing: border-box;"><a href="https://cbcs.endao.co/" target="_blank" style="color: rgb(255, 129, 36); box-sizing: border-box;" _href="https://cbcs.endao.co/"><span style="color: #FF8124; box-sizing: border-box;">点击了解更多→&nbsp;cbcs.endao.co</span></a>
				</p></section></section></section><section style="padding: 0px 12px; letter-spacing: 0.4px; line-height: 1.8; font-size: 16px; box-sizing: border-box;" class="_135editor"><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p></section><section style="display: flex; flex-flow: row nowrap; margin: 10px 0%; text-align: center; justify-content: center; position: static; box-sizing: border-box;" class="_135editor"><section style="box-sizing:border-box;display: inline-block; vertical-align: middle; width: auto; flex: 0 0 0%; align-self: center; height: auto; margin: 0px; padding: 0px; box-shadow: rgb(0, 0, 0) 0px 0px 0px;"><section style="display: flex; flex-flow: row nowrap; justify-content: center; margin: -1px 0% 5px; position: static; box-sizing: border-box;"><section style="box-sizing:border-box;display: inline-block; vertical-align: bottom; width: auto; align-self: flex-end; flex: 0 0 0%; line-height: 0; letter-spacing: 0px; height: auto;"><section style="margin: 8px 0% -5px; position: static; box-sizing: border-box;transform: translate3d(1px, 0px, 0px);-webkit-transform: translate3d(1px, 0px, 0px);-moz-transform: translate3d(1px, 0px, 0px);-o-transform: translate3d(1px, 0px, 0px);"><section class="group-empty" style="box-sizing:border-box;display: inline-block; width: 6px; height: 6px; vertical-align: top; overflow: hidden; border-style: solid; border-width: 1px; border-radius: 50px 0px 50px 50px; border-color: rgb(255, 197, 41);"><svg viewbox="0 0 1 1" style="box-sizing:border-box;float:left;line-height:0;width:0;vertical-align:top;"></svg></section></section></section><section class="group-empty" style="box-sizing:border-box;display: inline-block; vertical-align: top; width: 22px; flex: 0 0 auto; align-self: stretch; height: auto; border-style: none none solid solid; border-width: 1px;  border-color: rgb(62, 62, 62) rgb(62, 62, 62) rgb(255, 197, 41) rgb(255, 197, 41);"><svg viewbox="0 0 1 1" style="box-sizing:border-box;float:left;line-height:0;width:0;vertical-align:top;"></svg></section></section></section><section style="box-sizing:border-box;display: inline-block; vertical-align: middle; width: auto; align-self: center; flex: 100 100 0%;"><section style="margin: 2px 0% 0px; position: static; box-sizing: border-box;"><section style="background-color: rgb(255, 197, 41); height: 1px; box-sizing: border-box;"><svg viewbox="0 0 1 1" style="box-sizing:border-box;float:left;line-height:0;width:0;vertical-align:top;"></svg></section></section></section></section><section style="padding: 0px 12px; letter-spacing: 0.4px; line-height: 1.8; font-size: 16px; box-sizing: border-box;" class="_135editor"><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="color: #3E3E3E; font-size: 12px; letter-spacing: 0.4px; box-sizing: border-box;">[1]&nbsp;约翰·奥斯华，《房角石圣经注释丛书第一卷下：出埃及记》，侯春彦译（香港：恩道出版社，2019），46。</span><br style="box-sizing: border-box;"/>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="font-size: 12px; color: #3E3E3E; box-sizing: border-box;">[2]&nbsp;同上。</span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="font-size: 12px; color: #3E3E3E; box-sizing: border-box;">[3]&nbsp;奥斯华，《房角石圣经注释丛书第一卷下：出埃及记》，47。</span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="font-size: 12px; color: #3E3E3E; box-sizing: border-box;">[4]&nbsp;奥斯华，《房角石圣经注释丛书第一卷下：出埃及记》，241。</span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="font-size: 12px; color: #3E3E3E; box-sizing: border-box;">[5]&nbsp;奥斯华，《房角石圣经注释丛书第一卷下：出埃及记》，47。</span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="font-size: 12px; color: #3E3E3E; box-sizing: border-box;">[6]&nbsp;奥斯华，《房角石圣经注释丛书第一卷下：出埃及记》，89。</span>
		</p></section></section>

          
          <!-- 内容结束 -->
        </div>
      </div>
    </div>
  </div>
  <?php include "../footer.html" ?>
</body>

</html>