<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="zh-CN" lang="zh-CN" >
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="房角石圣经注释丛书">
  <meta name="keywords" content="房角石圣经注释丛书">
  <title>耶稣为何常常与人一起吃饭？-路加福音-房角石圣经注释丛书</title>
  <link rel="shortcut icon" href="../assets/img/favicon.png">
  <link rel="stylesheet" href="../assets/css/styles.css">

</head>
<body>
  <div class="content-wrapper">
    <?php include "../header.html" ?>
    <div class="container">
      <div class="row py-16">
        <div class="col-xl-6 col-md-10 col-lg-6 order-xl-2 mx-auto">
          <!-- 内容开始 -->

          <section style="box-sizing: border-box;   text-align: justify; font-size: 16px;"><section style="margin: 10px 0px; text-align: left; justify-content: flex-start; display: flex; flex-flow: row nowrap; position: static; box-sizing: border-box;" class="_135editor"><section style="box-sizing:border-box;display: inline-block; vertical-align: bottom; width: auto; min-width: 10%; max-width: 100%; flex: 0 0 auto; height: auto; align-self: flex-end; margin: 0px -20px 0px 0px;"><section style="text-align: center; margin: 0px; position: static; box-sizing: border-box;"><section class="group-empty" style="box-sizing:border-box;display: inline-block; width: 47px; height: 47px; vertical-align: top; overflow: hidden; border-width: 0px; border-radius: 77px; border-style: solid; border-color: rgb(62, 62, 62); background-image: linear-gradient(to top, rgb(255, 243, 173) 0%, rgba(255, 243, 173, 0) 100%);"><svg viewbox="0 0 1 1" style="box-sizing:border-box;float:left;line-height:0;width:0;vertical-align:top;"></svg></section></section></section><section style="box-sizing:border-box;display: inline-block; vertical-align: bottom; width: auto; min-width: 10%; max-width: 100%; flex: 0 0 auto; height: auto; align-self: flex-end;"><section style="text-align: center; box-sizing: border-box;"><p style="margin: 0px; padding: 0px; box-sizing: border-box;"><strong style="box-sizing: border-box;">编 &nbsp;辑 &nbsp;分 &nbsp;享 ✦</strong>
				</p></section><section style="margin: 0px; position: static; box-sizing: border-box;"><section style="font-size: 14px; text-align: justify; box-sizing: border-box;"><p style="text-align:left;  margin: 0px; padding: 0px; box-sizing: border-box;"><span style="background-color: #3E3E3E; color: #FFFFFF; box-sizing: border-box;">&nbsp;Editor‘s Sharing&nbsp;</span>
					</p></section></section></section></section><section style="text-align: center; font-size: 24px; box-sizing: border-box;" class="_135editor"><p style="margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p><p style="margin: 0px; padding: 0px; box-sizing: border-box;"><strong style="box-sizing: border-box;">耶稣为何常常与人一起吃饭？</strong>
		</p><p style="margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p></section><section style="margin: 0px 0%; text-align: left; justify-content: flex-start; display: flex; flex-flow: row nowrap; position: static; box-sizing: border-box;" class="_135editor"><section style="box-sizing:border-box;max-width: 100% !important;display: inline-block; width: 100%; vertical-align: top; padding: 20px; align-self: flex-start; flex: 0 0 auto; background-image: linear-gradient(to top, rgb(255, 243, 173) 0%, rgba(255, 243, 173, 0) 100%);"><section style="text-align: center; margin: 0px 0% 20px; line-height: 0; position: static; box-sizing: border-box;"><section style="box-sizing:border-box;max-width: 100%; vertical-align: middle; display: inline-block; line-height: 0; width: 90%; height: auto;"><img class="raw-image" style="box-sizing:border-box;vertical-align: middle; width: 100%;" _width="100%" src="https://ehome.endao.co/book_image/detail/1670320633396.jpg" draggable="false" _src="https://img.xiumi.us/xmi/ua/3O1Ws/i/a6f55e8b323dde8db62790dfef7b4bbf-sz_282884.jpg"/>
				</section></section><section style="color: rgb(0, 0, 0); text-align: justify; font-size: 15px; letter-spacing: 0.4px; line-height: 1.8; padding: 0px 12px; box-sizing: border-box;"><p style=" margin: 0px; padding: 0px; box-sizing: border-box;">路加福音记载了耶稣的十次筵席。从特莱茨博士描述的文化细节中，我们更深体会到主耶稣常常与人坐席的原因之一：</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><strong style="box-sizing: border-box;">将神的饶恕与接纳带给那些被社会排斥的边缘人。</strong>
				</p></section></section></section><section style="letter-spacing: 0.4px; line-height: 1.8; padding: 0px 12px; box-sizing: border-box;" class="_135editor"><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p><p style="text-align:right;  margin: 0px; padding: 0px; box-sizing: border-box;"><span style="color: #000000; box-sizing: border-box;"><strong style="box-sizing: border-box;"><span style="color: #000000; box-sizing: border-box;">文</span></strong><span style="color: #000000; box-sizing: border-box;"> | 柯言</span></span>
		</p><p style="text-align:right;  margin: 0px; padding: 0px; box-sizing: border-box;"><span style="color: #000000; box-sizing: border-box;"><span style="font-size: 15px; box-sizing: border-box;"><br style="box-sizing: border-box;"/></span></span>
		</p><p style="text-align:right;  margin: 0px; padding: 0px; box-sizing: border-box;"><span style="color: #000000; box-sizing: border-box;"><span style="font-size: 15px; box-sizing: border-box;"><br style="box-sizing: border-box;"/></span></span>
		</p></section><section style="padding: 0px 12px; letter-spacing: 0.4px; line-height: 1.9; color: rgb(0, 0, 0); box-sizing: border-box;" class="_135editor"><p style=" margin: 0px; padding: 0px; box-sizing: border-box;">在我的家乡，有一种近年来兴起的“吃饭文化”。朋友相聚，各人都尽量做一次东道主。倘若第一顿饭有4方代表出席，那最后多半会变成4次饭局！吃饭文化变得一言难尽……</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;">主耶稣却常常和众人一起吃饭。四福音书有多处描述耶稣与人同坐筵席的场景，其中记载次数最多的是路加福音，共10次。<span style="color: #FFCA00; box-sizing: border-box;">[1]</span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;">并非每次筵席都是宾主尽欢。特莱茨指出，马大和马利亚接耶稣去她们家，动词“<span style="color: #FF8124; box-sizing: border-box;">接待</span>”是hupodechomai，表示<span style="color: #FF8124; box-sizing: border-box;">非常热情的待客方式</span>（路10:38）。撒该接待耶稣，也是这个动词（和合本译为“欢欢喜喜地接待”）。但是法利赛人邀请耶稣赴宴，却不是这个动词。特莱茨据此推测，邀请耶稣的筵席中，有一部分或许是“<span style="color: #FF8124; box-sizing: border-box;">怀有敌意的场合</span>”。<span style="color: #FFCA00; box-sizing: border-box;">[2]</span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;">主耶稣为何常与众人一起吃吃喝喝？他甚至与那些怀疑他的法利赛人同席，还要接受他们的挑战？</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;">主耶稣自己曾在撒该家的筵席上回答这个问题：“<span style="color: #FF8124; box-sizing: border-box;">人子来，为要寻找、拯救失丧的人。</span>”（路19:10）。所以他走入人间，在旅途中、在筵席上、在教导里，去寻找那些如羊走迷的人，带给他们神的饶恕和接纳。</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;">特莱茨博士对这些筵席的解读，除了经文的含义，还补充了<span style="color: #FF8124; box-sizing: border-box;">背后的文化细节</span>，帮助我们更深体会到主耶稣这句话的含义。</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p></section><section style="text-align: left; justify-content: flex-start; display: flex; flex-flow: row nowrap; margin: 10px 0px; position: static; box-sizing: border-box;" class="_135editor"><section style="box-sizing:border-box;display: inline-block; vertical-align: middle; width: auto; align-self: center; flex: 0 0 auto; min-width: 5%; max-width: 100%; height: auto; padding: 0px; margin: 0px 10px 0px 0px;"><section style="text-align: center; margin: 0px; position: static; box-sizing: border-box;"><section style="box-sizing:border-box;display: inline-block; width: 47px; height: 47px; vertical-align: top; overflow: hidden; border-width: 0px; border-radius: 410px; border-style: none; border-color: rgb(62, 62, 62); background-color: rgb(248, 208, 95); box-shadow: rgb(255, 255, 255) -11px -7px 25px inset;"><section style="text-align: justify; font-size: 28px; box-sizing: border-box;"><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
						</p></section></section></section></section><section style="box-sizing:border-box;display: inline-block; vertical-align: middle; width: auto; align-self: center; flex: 0 0 auto; min-width: 5%; max-width: 100%; height: auto; padding: 0px;"><section style="text-align: justify; font-size: 24px; color: rgb(0, 0, 0); box-sizing: border-box;"><p style=" margin: 0px; padding: 0px; box-sizing: border-box;">犯了罪的女子</p></section></section><section class="group-empty" style="box-sizing:border-box;display: inline-block; vertical-align: top; width: auto; min-width: 5%; max-width: 100%; flex: 0 0 auto; height: auto; margin: 0px 0px 0px 15px;"><svg viewbox="0 0 1 1" style="box-sizing:border-box;float:left;line-height:0;width:0;vertical-align:top;"></svg></section></section><section style="padding: 0px 12px; letter-spacing: 0.4px; line-height: 1.9; color: rgb(0, 0, 0); box-sizing: border-box;" class="_135editor"><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;">一个突出的例子，在第七章法利赛人的筵席。来了一位犯了罪的女子，她“站在耶稣背后，挨着他的脚哭”（路7:38）。因为泪水滴在耶稣脚上，她就用头发擦耶稣的脚。</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;">特莱茨告诉我们，“在当时的犹太社会，女人当众解开自己的头发是不体面的做法，会引人非议”。<span style="color: #FFCA00; box-sizing: border-box;">[3]</span>我们想象一下这位女子的处境：犯了罪，人尽皆知，却还去了法利赛人的筵席，还不顾体面，解开自己的头发——她是多么绝望，才有这一系列的行为！<span style="color: #FFCA00; box-sizing: border-box;">[4]</span>这样一个人，被她的族群拒绝，只能拿着盛了香膏的玉瓶去见耶稣（路7:37），几乎是献上自己最后的、唯一体面的“祭”。</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;">然而，在众多鄙视她的法利赛人面前，<span style="color: #FF8124; box-sizing: border-box;">耶稣接纳了她的行为，更赦免了她的罪</span>（路7:48）。</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p></section><section style="text-align: left; justify-content: flex-start; display: flex; flex-flow: row nowrap; margin: 10px 0px; position: static; box-sizing: border-box;" class="_135editor"><section style="box-sizing:border-box;display: inline-block; vertical-align: middle; width: auto; align-self: center; flex: 0 0 auto; min-width: 5%; max-width: 100%; height: auto; padding: 0px; margin: 0px 10px 0px 0px;"><section style="text-align: center; margin: 0px; position: static; box-sizing: border-box;"><section style="box-sizing:border-box;display: inline-block; width: 47px; height: 47px; vertical-align: top; overflow: hidden; border-width: 0px; border-radius: 410px; border-style: none; border-color: rgb(62, 62, 62); background-color: rgb(248, 208, 95); box-shadow: rgb(255, 255, 255) -11px -7px 25px inset;"><section style="text-align: justify; font-size: 28px; box-sizing: border-box;"><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
						</p></section></section></section></section><section style="box-sizing:border-box;display: inline-block; vertical-align: middle; width: auto; align-self: center; flex: 0 0 auto; min-width: 5%; max-width: 100%; height: auto; padding: 0px;"><section style="text-align: justify; font-size: 24px; color: rgb(0, 0, 0); box-sizing: border-box;"><p style=" margin: 0px; padding: 0px; box-sizing: border-box;">税吏利未</p></section></section><section class="group-empty" style="box-sizing:border-box;display: inline-block; vertical-align: top; width: auto; min-width: 5%; max-width: 100%; flex: 0 0 auto; height: auto; margin: 0px 0px 0px 15px;"><svg viewbox="0 0 1 1" style="box-sizing:border-box;float:left;line-height:0;width:0;vertical-align:top;"></svg></section></section><section style="padding: 0px 12px; letter-spacing: 0.4px; line-height: 1.9; color: rgb(0, 0, 0); box-sizing: border-box;" class="_135editor"><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;">还有其他类似的例子，讲述耶稣如何借助筵席去寻找、拯救失丧的人。</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;">他接受利未的邀请，去利未家里和很多税吏与罪人一起吃饭（路5:29-37）。税吏也游离于以色列群体之外，被这个族群所鄙视。“人们憎恶税吏，因为他们以欺诈著称，且被视为……叛徒。”<span style="color: #FFCA00; box-sizing: border-box;">[5]</span>&nbsp;可是耶稣却呼召这样的“叛徒”作自己的门徒（路5:27）。</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p></section><section style="text-align: left; justify-content: flex-start; display: flex; flex-flow: row nowrap; margin: 10px 0px; position: static; box-sizing: border-box;" class="_135editor"><section style="box-sizing:border-box;display: inline-block; vertical-align: middle; width: auto; align-self: center; flex: 0 0 auto; min-width: 5%; max-width: 100%; height: auto; padding: 0px; margin: 0px 10px 0px 0px;"><section style="text-align: center; margin: 0px; position: static; box-sizing: border-box;"><section style="box-sizing:border-box;display: inline-block; width: 47px; height: 47px; vertical-align: top; overflow: hidden; border-width: 0px; border-radius: 410px; border-style: none; border-color: rgb(62, 62, 62); background-color: rgb(248, 208, 95); box-shadow: rgb(255, 255, 255) -11px -7px 25px inset;"><section style="text-align: justify; font-size: 28px; box-sizing: border-box;"><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
						</p></section></section></section></section><section style="box-sizing:border-box;display: inline-block; vertical-align: middle; width: auto; align-self: center; flex: 0 0 auto; min-width: 5%; max-width: 100%; height: auto; padding: 0px;"><section style="text-align: justify; font-size: 24px; color: rgb(0, 0, 0); box-sizing: border-box;"><p style=" margin: 0px; padding: 0px; box-sizing: border-box;">税吏撒该</p></section></section><section class="group-empty" style="box-sizing:border-box;display: inline-block; vertical-align: top; width: auto; min-width: 5%; max-width: 100%; flex: 0 0 auto; height: auto; margin: 0px 0px 0px 15px;"><svg viewbox="0 0 1 1" style="box-sizing:border-box;float:left;line-height:0;width:0;vertical-align:top;"></svg></section></section><section style="padding: 0px 12px; letter-spacing: 0.4px; line-height: 1.9; color: rgb(0, 0, 0); box-sizing: border-box;" class="_135editor"><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;">路加记载的第七个筵席是在撒该家里。撒该也是税吏，甚至因为身材矮小，几乎连瞅一眼耶稣的机会都没有，只能爬上桑树，才得以看见耶稣的样貌。然而耶稣却主动叫出了撒该的名字，还去他家里吃饭住宿（路19:1-10）。</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p></section><section style="text-align: left; justify-content: flex-start; display: flex; flex-flow: row nowrap; margin: 10px 0px; position: static; box-sizing: border-box;" class="_135editor"><section style="box-sizing:border-box;display: inline-block; vertical-align: middle; width: auto; align-self: center; flex: 0 0 auto; min-width: 5%; max-width: 100%; height: auto; padding: 0px; margin: 0px 10px 0px 0px;"><section style="text-align: center; margin: 0px; position: static; box-sizing: border-box;"><section style="box-sizing:border-box;display: inline-block; width: 47px; height: 47px; vertical-align: top; overflow: hidden; border-width: 0px; border-radius: 410px; border-style: none; border-color: rgb(62, 62, 62); background-color: rgb(248, 208, 95); box-shadow: rgb(255, 255, 255) -11px -7px 25px inset;"><section style="text-align: justify; font-size: 28px; box-sizing: border-box;"><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
						</p></section></section></section></section><section style="box-sizing:border-box;display: inline-block; vertical-align: middle; width: auto; align-self: center; flex: 0 0 auto; min-width: 5%; max-width: 100%; height: auto; padding: 0px;"><section style="text-align: justify; font-size: 24px; color: rgb(0, 0, 0); box-sizing: border-box;"><p style=" margin: 0px; padding: 0px; box-sizing: border-box;">总结</p></section></section><section class="group-empty" style="box-sizing:border-box;display: inline-block; vertical-align: top; width: auto; min-width: 5%; max-width: 100%; flex: 0 0 auto; height: auto; margin: 0px 0px 0px 15px;"><svg viewbox="0 0 1 1" style="box-sizing:border-box;float:left;line-height:0;width:0;vertical-align:top;"></svg></section></section><section style="padding: 0px 12px; letter-spacing: 0.4px; line-height: 1.8; font-size: 15px; color: rgb(0, 0, 0); box-sizing: border-box;" class="_135editor"><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p></section><section style="padding: 0px 12px; letter-spacing: 0.4px; line-height: 1.9; color: rgb(0, 0, 0); box-sizing: border-box;" class="_135editor"><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="letter-spacing: 0.4px; box-sizing: border-box;">谁配得赦免与永生呢？那些世界所认定的“罪人”，那些被世界排斥、身居社会边缘的人，他们有机会看见耶稣吗？有机会听到福音吗？</span><br style="box-sizing: border-box;"/>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="letter-spacing: 0.4px; box-sizing: border-box;"><br style="box-sizing: border-box;"/></span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="letter-spacing: 0.4px; box-sizing: border-box;">经文告诉我们，主耶稣<span style="letter-spacing: 0.4px; color: #FF8124; box-sizing: border-box;">借助筵席，</span><span style="letter-spacing: 0.4px; color: #FF8124; box-sizing: border-box;">打破了社会的等级界限，主动去寻找这些边缘人，</span>让他们能够看见他，靠近他，听到神赦罪的福音。</span><br style="box-sizing: border-box;"/>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;">特莱茨在解释路加福音14:12-14（关于筵席座次的比喻）时，这样说：</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br/>
		</p></section><section style="margin: 10px 0%; text-align: left; justify-content: flex-start; display: flex; flex-flow: row nowrap; position: static; box-sizing: border-box;" class="_135editor"><section style="box-sizing:border-box;max-width: 100% !important;display: inline-block; width: 100%; vertical-align: top; padding: 15px; background-position: 25.8037% -43.1473%; background-repeat: repeat; background-size: 29.7866%; background-attachment: scroll; align-self: flex-start; flex: 0 0 auto; background-image: url(&quot;https://statics.xiumi.us/stc/images/templates-assets/tpl-paper/image/7327d0ed0097743275838846769faebb-sz_3523.png&quot;);"><section style="text-align: justify; box-sizing: border-box;" class="_135editor"><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
				</p></section><section style="color: rgb(62, 62, 62); text-align: justify; font-size: 15px; line-height: 1.9; letter-spacing: 0.4px; padding: 0px 12px; box-sizing: border-box;" class="_135editor"><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="caret-color: #000000; letter-spacing: 0.4px; box-sizing: border-box;">耶稣告诫所谈论的那个人不要宴请自己的同伴或同类的人，即亲朋好友、同事邻里这些他习惯往来的人。这些人无疑可以报答他的善意，并按照礼尚往来的习惯，用同样好客的方式回请他。本质上这不过是</span><span style="caret-color: #000000; letter-spacing: 0.4px; color: #FF8124; box-sizing: border-box;"><strong style="box-sizing: border-box;">等价交换</strong></span><span style="caret-color: #000000; letter-spacing: 0.4px; box-sizing: border-box;">（quid pro quo），长时间来看双方都不吃亏。但是，在耶稣看来，那即将来临的神国将彻底颠覆这种模式：“倒要请那贫穷的、残废的、瘸腿的、瞎眼的。”（路14:13；留意这些人也受邀出席14:21的大筵席）这些穷困残障的人</span><span style="caret-color: #000000; letter-spacing: 0.4px; color: #FF8124; box-sizing: border-box;"><strong style="box-sizing: border-box;">无法回报</strong></span><span style="caret-color: #000000; letter-spacing: 0.4px; box-sizing: border-box;">他们所得到的善意款待。邀请他们就成了完全出于怜悯和恩典而善待关爱他人的举动。</span><span style="caret-color: #000000; letter-spacing: 0.4px; color: #FFCA00; box-sizing: border-box;">[6]</span><br style="box-sizing: border-box;"/>
				</p></section><section style="text-align: justify; box-sizing: border-box;" class="_135editor"><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
				</p></section></section></section><section style="padding: 0px 12px; letter-spacing: 0.4px; line-height: 1.9; color: rgb(0, 0, 0); box-sizing: border-box;" class="_135editor"><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="letter-spacing: 0.4px; box-sizing: border-box;"><br style="box-sizing: border-box;"/></span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="letter-spacing: 0.4px; box-sizing: border-box;">耶稣时代的筵席有它自身的传统和社会角色，<span style="letter-spacing: 0.4px; color: #FFCA00; box-sizing: border-box;">[7]</span>但主耶稣打破了那些人为的界限，将神的赦免和接纳赐给社会的边缘人。</span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="letter-spacing: 0.4px; box-sizing: border-box;"><br style="box-sizing: border-box;"/></span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="letter-spacing: 0.4px; box-sizing: border-box;">今天的吃饭文化也有各种情谊或缘由在其中，有它存在的意义和必要。但它是否把参与者限定在一个礼尚往来的圈子里？是否像主耶稣那样，打破人为的社会等级界限，去邀请那些“贫穷的、残废的、瘸腿的、瞎眼的”？我们基督徒身处这样的饭局文化中，该如何回应呢？</span><br style="box-sizing: border-box;"/>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;">倘若那时的文化潮流不是筵席，而是咖啡馆、民俗馆，主耶稣也一定会常常去那里与人一起喝咖啡、看民俗。他也同样会遭到质疑。但他依然会去，因为“<span style="color: #FF8124; box-sizing: border-box;">人子来，为要寻找、拯救失丧的人</span>”（路19:10）。</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p></section><section style="margin: 0px 0%; text-align: left; justify-content: flex-start; display: flex; flex-flow: row nowrap; position: static; box-sizing: border-box;" class="_135editor"><section style="box-sizing:border-box;max-width: 100% !important;display: inline-block; width: 100%; vertical-align: top; padding: 20px; align-self: flex-start; flex: 0 0 auto; background-image: linear-gradient(to top, rgb(255, 243, 173) 0%, rgba(255, 243, 173, 0) 100%);"><section style="text-align: center; margin: 0px 0% 20px; line-height: 0; position: static; box-sizing: border-box;"><section style="box-sizing:border-box;max-width: 100%; vertical-align: middle; display: inline-block; line-height: 0; width: 60%; height: auto;"><img class="raw-image" style="box-sizing:border-box;vertical-align: middle; width: 100%;" _width="100%" src="https://ehome.endao.co/book_image/detail/1669887987892.png" draggable="false" _src="https://img.xiumi.us/xmi/ua/3O1Ws/i/06486484a6d3c53eb584ac03bbe449d9-sz_1979970.png"/>
				</section></section><section style="color: rgb(0, 0, 0); text-align: justify; letter-spacing: 0.4px; line-height: 1.9; padding: 0px 12px; box-sizing: border-box;"><p style="text-align:center;  margin: 0px; padding: 0px; box-sizing: border-box;"><strong style="box-sizing: border-box;">✦ &nbsp;房角石</strong><strong style="letter-spacing: 0.4px; box-sizing: border-box;">圣经注释丛书&nbsp; ✦</strong>
				</p><p style="text-align:center;  margin: 0px; padding: 0px; box-sizing: border-box;"><strong style="box-sizing: border-box;"><span style="background-color: #FFCA00; color: #FFFFFF; box-sizing: border-box;">全套34册 | 简体/繁體</span></strong>
				</p><p style="text-align:center;  margin: 0px; padding: 0px; box-sizing: border-box;"><span style="text-decoration: none; color: #000000; box-sizing: border-box;">人人都能读的高品质释经书</span>
				</p><p style="text-align:center;  margin: 0px; padding: 0px; box-sizing: border-box;"><a href="https://cbcs.endao.co/" target="_blank" style="color: rgb(255, 129, 36); box-sizing: border-box;" _href="https://cbcs.endao.co/"><span style="color: #FF8124; box-sizing: border-box;">点击了解更多→&nbsp;cbcs.endao.co</span></a>
				</p></section></section></section><p style=" margin: 0px; padding: 0px; box-sizing: border-box;" class="_135editor"><br style="box-sizing: border-box;"/>
	</p><section style="display: flex; flex-flow: row nowrap; margin: 10px 0%; text-align: center; justify-content: center; position: static; box-sizing: border-box;" class="_135editor"><section style="box-sizing:border-box;display: inline-block; vertical-align: middle; width: auto; flex: 0 0 0%; align-self: center; height: auto; margin: 0px; padding: 0px; box-shadow: rgb(0, 0, 0) 0px 0px 0px;"><section style="display: flex; flex-flow: row nowrap; justify-content: center; margin: -1px 0% 5px; position: static; box-sizing: border-box;"><section style="box-sizing:border-box;display: inline-block; vertical-align: bottom; width: auto; align-self: flex-end; flex: 0 0 0%; line-height: 0; letter-spacing: 0px; height: auto;"><section style="margin: 8px 0% -5px; position: static; box-sizing: border-box;transform: translate3d(1px, 0px, 0px);-webkit-transform: translate3d(1px, 0px, 0px);-moz-transform: translate3d(1px, 0px, 0px);-o-transform: translate3d(1px, 0px, 0px);"><section class="group-empty" style="box-sizing:border-box;display: inline-block; width: 6px; height: 6px; vertical-align: top; overflow: hidden; border-style: solid; border-width: 1px; border-radius: 50px 0px 50px 50px; border-color: rgb(255, 197, 41);"><svg viewbox="0 0 1 1" style="box-sizing:border-box;float:left;line-height:0;width:0;vertical-align:top;"></svg></section></section></section><section class="group-empty" style="box-sizing:border-box;display: inline-block; vertical-align: top; width: 22px; flex: 0 0 auto; align-self: stretch; height: auto; border-style: none none solid solid; border-width: 1px;  border-color: rgb(62, 62, 62) rgb(62, 62, 62) rgb(255, 197, 41) rgb(255, 197, 41);"><svg viewbox="0 0 1 1" style="box-sizing:border-box;float:left;line-height:0;width:0;vertical-align:top;"></svg></section></section></section><section style="box-sizing:border-box;display: inline-block; vertical-align: middle; width: auto; align-self: center; flex: 100 100 0%;"><section style="margin: 2px 0% 0px; position: static; box-sizing: border-box;"><section style="background-color: rgb(255, 197, 41); height: 1px; box-sizing: border-box;"><svg viewbox="0 0 1 1" style="box-sizing:border-box;float:left;line-height:0;width:0;vertical-align:top;"></svg></section></section></section></section><section style="padding: 0px 12px; box-sizing: border-box;" class="_135editor"><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="font-size: 12px; color: #3E3E3E; box-sizing: border-box;">[1] 十次是依据特莱茨（2021）的解析。</span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="font-size: 12px; color: #3E3E3E; box-sizing: border-box;">[2] 阿利森·特莱茨，《房角石圣经注释丛书第十二卷上：路加福音》，任涛译（香港：恩道出版社，2021），267。</span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="font-size: 12px; color: #3E3E3E; box-sizing: border-box;">[3] 特莱茨，《房角石圣经注释丛书第十二卷上：路加福音》，200。</span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="font-size: 12px; color: #3E3E3E; box-sizing: border-box;">[4] 特莱茨认为，这位女子解开头发，可能是因为对习俗麻木，但更可能是“因悔改和感恩而放开自己，不受约束”，201。</span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="font-size: 12px; color: #3E3E3E; box-sizing: border-box;">[5] 特莱茨，《房角石圣经注释丛书第十二卷上：路加福音》，161。</span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="font-size: 12px; color: #3E3E3E; box-sizing: border-box;">[6] 特莱茨，《房角石圣经注释丛书第十二卷上：路加福音》，323。</span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="font-size: 12px; color: #3E3E3E; box-sizing: border-box;">[7] Jamir Lanuwabang, <em style="box-sizing: border-box;">Exclusion and Judgment in Fellowship Meals: The Socio-historical Background of 1 Corinthians 11:17–34</em>. The Lutterworth Press, James Clarke &amp; Co Ltd, 2016.</span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p></section></section>

          
          <!-- 内容结束 -->
        </div>
      </div>
    </div>
  </div>
  <?php include "../footer.html" ?>
</body>

</html>