<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="zh-CN" lang="zh-CN" >
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="房角石圣经注释丛书">
  <meta name="keywords" content="房角石圣经注释丛书">
  <title>我的自由为何不能我做主？-哥林多前后书-房角石圣经注释丛书</title>
  <link rel="shortcut icon" href="../assets/img/favicon.png">
  <link rel="stylesheet" href="../assets/css/styles.css">

</head>
<body>
  <div class="content-wrapper">
    <?php include "../header.html" ?>
    <div class="container">
      <div class="row py-16">
        <div class="col-xl-6 col-md-10 col-lg-6 order-xl-2 mx-auto">
          <!-- 内容开始 -->

          <section style="font-size: 15px; color: rgb(0, 0, 0); letter-spacing: 0.4px; line-height: 1.8; padding: 0px 12px; box-sizing: border-box;   text-align: justify;"><section style="margin: 10px 0px; text-align: left; justify-content: flex-start; display: flex; flex-flow: row nowrap; position: static; box-sizing: border-box;" class="_135editor"><section style="box-sizing:border-box;display: inline-block; vertical-align: bottom; width: auto; min-width: 10%; max-width: 100%; flex: 0 0 auto; height: auto; align-self: flex-end; margin: 0px -20px 0px 0px;"><section style="text-align: center; margin: 0px; position: static; box-sizing: border-box;"><section class="group-empty" style="box-sizing:border-box;display: inline-block; width: 47px; height: 47px; vertical-align: top; overflow: hidden; border-width: 0px; border-radius: 77px; border-style: solid; border-color: rgb(62, 62, 62); background-image: linear-gradient(to top, rgb(255, 243, 173) 0%, rgba(255, 243, 173, 0) 100%);"><svg viewbox="0 0 1 1" style="box-sizing:border-box;float:left;line-height:0;width:0;vertical-align:top;"></svg></section></section></section><section style="box-sizing:border-box;display: inline-block; vertical-align: bottom; width: auto; min-width: 10%; max-width: 100%; flex: 0 0 auto; height: auto; align-self: flex-end;"><section style="text-align: center; box-sizing: border-box;"><p style="margin: 0px; padding: 0px; box-sizing: border-box;"><strong style="box-sizing: border-box;">编 &nbsp;辑 &nbsp;分 &nbsp;享 ✦</strong>
				</p></section><section style="margin: 0px; position: static; box-sizing: border-box;"><section style="font-size: 13px; text-align: justify; box-sizing: border-box;"><p style="text-align:left;  margin: 0px; padding: 0px; box-sizing: border-box;"><span style="background-color: #3E3E3E; color: #FFFFFF; box-sizing: border-box;">&nbsp;Editor‘s Sharing&nbsp;</span>
					</p></section></section></section></section><section style="text-align: center; font-size: 24px; box-sizing: border-box;" class="_135editor"><p style="margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p><p style="margin: 0px; padding: 0px; box-sizing: border-box;"><strong style="box-sizing: border-box;">我的自由为何不能我做主？</strong>
		</p><p style="margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p></section><section style="margin: 0px 0%; text-align: left; justify-content: flex-start; display: flex; flex-flow: row nowrap; position: static; box-sizing: border-box;" class="_135editor"><section style="box-sizing:border-box;max-width: 100% !important;display: inline-block; width: 100%; vertical-align: top; padding: 20px; align-self: flex-start; flex: 0 0 auto; background-image: linear-gradient(to top, rgb(255, 243, 173) 0%, rgba(255, 243, 173, 0) 100%);"><section style="text-align: center; margin: 0px 0% 20px; line-height: 0; position: static; box-sizing: border-box;"><section style="box-sizing:border-box;max-width: 100%; vertical-align: middle; display: inline-block; line-height: 0; width: 90%; height: auto;"><img class="raw-image" style="box-sizing:border-box;vertical-align: middle; width: 100%;" _width="100%" src="https://ehome.endao.co/book_image/detail/1670320710305.jpg" draggable="false" _src="https://img.xiumi.us/xmi/ua/3O1Ws/i/a875f501cef84633b754509ca3ed1900-sz_76555.jpg"/>
				</section></section><section style="color: rgb(0, 0, 0); text-align: justify; letter-spacing: 0.4px; line-height: 1.8; padding: 0px 12px; box-sizing: border-box;"><p style=" margin: 0px; padding: 0px; box-sizing: border-box;">哥林多信徒可不可以吃祭肉？</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;">保罗说可以吃，但若使弟兄跌倒，就该放弃这一自由。因为在基督徒的生命中，排在第一的永远是<strong style="box-sizing: border-box;">爱</strong>。</p></section></section></section><section style="letter-spacing: 0.4px; line-height: 1.8; padding: 0px 12px; font-size: 16px; box-sizing: border-box;" class="_135editor"><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p><p style="text-align:right;  margin: 0px; padding: 0px; box-sizing: border-box;"><span style="color: #000000; box-sizing: border-box;"><strong style="box-sizing: border-box;"><span style="color: #000000; box-sizing: border-box;">文</span></strong><span style="color: #000000; box-sizing: border-box;"> | 贝果</span></span>
		</p><p style="text-align:right;  margin: 0px; padding: 0px; box-sizing: border-box;"><span style="color: #000000; box-sizing: border-box;"><span style="font-size: 15px; box-sizing: border-box;"><br style="box-sizing: border-box;"/></span></span>
		</p><p style="text-align:right;  margin: 0px; padding: 0px; box-sizing: border-box;"><span style="color: #000000; box-sizing: border-box;"><span style="font-size: 15px; box-sizing: border-box;"><br style="box-sizing: border-box;"/></span></span>
		</p></section><section style="padding: 0px 12px; letter-spacing: 0.4px; line-height: 1.9; font-size: 16px; color: rgb(0, 0, 0); box-sizing: border-box;" class="_135editor"><section class="_135editor" data-role="list"><ul class="list-paddingleft-2" style="list-style-type: disc;"><li><p style="margin: 0px; padding: 0px; box-sizing: border-box;">知识与爱心，孰轻孰重？</p></li><li><p style="margin: 0px; padding: 0px; box-sizing: border-box;">身为基督徒，与非基督徒打交道有何忌讳？何事能做，何事不能做？</p></li><li><p style="margin: 0px; padding: 0px; box-sizing: border-box;">与不同背景和信仰传统的信徒又该如何打交道？</p></li><li><p style="margin: 0px; padding: 0px; box-sizing: border-box;">我们该如何面对彼此在信仰上的不同意见和应用？</p></li></ul></section><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;">我想，这些问题是我们在信仰的不同阶段都会遇到的。早在一千多年前，哥林多信徒就曾向保罗求问过此类问题。那保罗是如何回应的？他的立场和原则能打开我们各自处境下的心结吗？相信威廉·贝克在《<span style="color: #FF8124; box-sizing: border-box;">房角石注释：哥林多前后书》</span>对哥林多前书8:1－13的释义会带我们找到答案。<span style="color: #FFCA00; box-sizing: border-box;">[1]</span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;">在这段经文里，保罗对哥林多人来信中有关食用偶像庙里祭肉的问题做出了回复。早先的耶路撒冷大会已一致通过要外邦归信者“禁戒偶像的污秽”（徒15:20），所以保罗肯定也曾将此事教导哥林多人。可见，此处保罗应对的很可能是他们新近才出现的情况和看法。</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;">保罗首先在第1节引述“多数派”（自称有知识的人，即强壮者）<span style="color: #FFCA00; box-sizing: border-box;">[2]</span>的话“我们都有知识”（8:1）。他们认为，有点知识的人都该同意其观点，即可以自由吃祭偶像之物。但保罗引述此话则是要他们尊重不同意见，要顾及对同一知识未能完全领会的“少数派”（没有这等知识的人，即软弱者）<span style="color: #FFCA00; box-sizing: border-box;">[3]</span>。于是保罗发出抨击：“知识是叫人自高自大”（8:1）。即使他们的知识是“对”的，其傲慢姿态已使其输掉争论。这种没有爱的态度非但不能造就人，还会损害他人的属灵生命，使软弱的人更加软弱。</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;">保罗继而引出悖论：过多知识加上自高自大就等于无知（8:2－3）。真正的知识意味着你明白知识是有限的。我们当追求的不光是知识，而是智慧，即加上爱和谦卑的知识。所以我们不是不要知识，而是说，没有爱调和的知识不仅无益，还有杀伤力，这也是保罗说“知识是叫人自高自大，<span style="color: #FF8124; box-sizing: border-box;">惟有爱心能造就人</span>”（8:1）的意思。</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;">在8:4－6，保罗讲明他们所共有的知识：神只有一位，偶像算不得什么。而且在当时的希罗文化下，众神的形象无处不在，因此，吃祭肉的问题不可避免。只是“<span style="color: #FF8124; box-sizing: border-box;">人不都有这等知识</span>”（8:7）。保罗非常理解少数派，明白他们是良心软弱，所知的真理没有完全融入到生活中。他们可能相信：偶像背后是敌对基督的鬼魔，会玷污新生命，所以吃祭肉是罪。</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;">在第8节，保罗申明自己的立场：吃祭偶像之肉不算什么。这既重申了多数派的观点，同时也在推翻这种观点。因为既然那不算什么，吃不吃都无妨，不会影响人与神的关系。第9－10节，保罗开始驳斥多数派，因他们轻视少数派，坚持行使自己的自由，进而使信心软弱者质疑委身生活的其他方面，以为什么都无所谓，以致最终丧失救恩。</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;">11－12节，保罗提出他反对多数派的理由：<span style="color: #000000; box-sizing: border-box;">他们得罪弟兄，也就得罪了为弟兄死的基督。</span>因为他们不肯为爱别人牺牲自己的权利，不肯像耶稣那样舍己。从中我们可以看到，“<span style="color: #FF8124; box-sizing: border-box;">不爱</span>”就等于是“<span style="color: #FF8124; box-sizing: border-box;">得罪</span>”，这一点让人颤栗。</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;">这一番论述下来，保罗最终得出他在吃祭肉问题上的结论：若使弟兄跌倒，祭肉就不值得吃（8:13）。保罗所教导的行事原则乃是，要为别人的益处行使自由。</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;">显然，这在今日教会内外的文化处境中依然适用。这样一来，很多“<span style="color: #FF8124; box-sizing: border-box;">我可不可以这样做？</span>”的问题就迎刃而解了。因为我们心里有了一把明明白白的尺子：</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;">爱人舍己始终排在“我的自由”之前。</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p></section><section style="margin: 0px 0%; text-align: left; justify-content: flex-start; display: flex; flex-flow: row nowrap; position: static; box-sizing: border-box;" class="_135editor"><section style="box-sizing:border-box;max-width: 100% !important;display: inline-block; width: 100%; vertical-align: top; padding: 20px; align-self: flex-start; flex: 0 0 auto; background-image: linear-gradient(to top, rgb(255, 243, 173) 0%, rgba(255, 243, 173, 0) 100%);"><section style="text-align: center; margin: 0px 0% 20px; line-height: 0; position: static; box-sizing: border-box;"><section style="box-sizing:border-box;max-width: 100%; vertical-align: middle; display: inline-block; line-height: 0; width: 60%; height: auto;"><img class="raw-image" style="box-sizing:border-box;vertical-align: middle; width: 100%;" _width="100%" src="https://ehome.endao.co/book_image/detail/1669887987892.png" draggable="false" _src="https://img.xiumi.us/xmi/ua/3O1Ws/i/06486484a6d3c53eb584ac03bbe449d9-sz_1979970.png"/>
				</section></section><section style="color: rgb(0, 0, 0); text-align: justify; font-size: 16px; letter-spacing: 0.4px; line-height: 1.9; padding: 0px 12px; box-sizing: border-box;"><p style="text-align:center;  margin: 0px; padding: 0px; box-sizing: border-box;"><strong style="box-sizing: border-box;">✦ &nbsp;房角石</strong><strong style="letter-spacing: 0.4px; box-sizing: border-box;">圣经注释丛书&nbsp; ✦</strong>
				</p><p style="text-align:center;  margin: 0px; padding: 0px; box-sizing: border-box;"><strong style="box-sizing: border-box;"><span style="background-color: #FFCA00; color: #FFFFFF; box-sizing: border-box;">全套34册 | 简体/繁體</span></strong>
				</p><p style="text-align:center;  margin: 0px; padding: 0px; box-sizing: border-box;"><span style="text-decoration: none; color: #000000; box-sizing: border-box;">人人都能读的高品质释经书</span>
				</p><p style="text-align:center;  margin: 0px; padding: 0px; box-sizing: border-box;"><a href="https://cbcs.endao.co/" target="_blank" style="color: rgb(255, 129, 36); box-sizing: border-box;" _href="https://cbcs.endao.co/"><span style="color: #FF8124; box-sizing: border-box;">点击了解更多→&nbsp;cbcs.endao.co</span></a>
				</p></section></section></section><section style="padding: 0px 12px; letter-spacing: 0.4px; line-height: 1.8; font-size: 16px; box-sizing: border-box;" class="_135editor"><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p></section><section style="display: flex; flex-flow: row nowrap; margin: 10px 0%; text-align: center; justify-content: center; position: static; box-sizing: border-box;" class="_135editor"><section style="box-sizing:border-box;display: inline-block; vertical-align: middle; width: auto; flex: 0 0 0%; align-self: center; height: auto; margin: 0px; padding: 0px; box-shadow: rgb(0, 0, 0) 0px 0px 0px;"><section style="display: flex; flex-flow: row nowrap; justify-content: center; margin: -1px 0% 5px; position: static; box-sizing: border-box;"><section style="box-sizing:border-box;display: inline-block; vertical-align: bottom; width: auto; align-self: flex-end; flex: 0 0 0%; line-height: 0; letter-spacing: 0px; height: auto;"><section style="margin: 8px 0% -5px; position: static; box-sizing: border-box;transform: translate3d(1px, 0px, 0px);-webkit-transform: translate3d(1px, 0px, 0px);-moz-transform: translate3d(1px, 0px, 0px);-o-transform: translate3d(1px, 0px, 0px);"><section class="group-empty" style="box-sizing:border-box;display: inline-block; width: 6px; height: 6px; vertical-align: top; overflow: hidden; border-style: solid; border-width: 1px; border-radius: 50px 0px 50px 50px; border-color: rgb(255, 197, 41);"><svg viewbox="0 0 1 1" style="box-sizing:border-box;float:left;line-height:0;width:0;vertical-align:top;"></svg></section></section></section><section class="group-empty" style="box-sizing:border-box;display: inline-block; vertical-align: top; width: 22px; flex: 0 0 auto; align-self: stretch; height: auto; border-style: none none solid solid; border-width: 1px;  border-color: rgb(62, 62, 62) rgb(62, 62, 62) rgb(255, 197, 41) rgb(255, 197, 41);"><svg viewbox="0 0 1 1" style="box-sizing:border-box;float:left;line-height:0;width:0;vertical-align:top;"></svg></section></section></section><section style="box-sizing:border-box;display: inline-block; vertical-align: middle; width: auto; align-self: center; flex: 100 100 0%;"><section style="margin: 2px 0% 0px; position: static; box-sizing: border-box;"><section style="background-color: rgb(255, 197, 41); height: 1px; box-sizing: border-box;"><svg viewbox="0 0 1 1" style="box-sizing:border-box;float:left;line-height:0;width:0;vertical-align:top;"></svg></section></section></section></section><section style="padding: 0px 12px; font-size: 16px; box-sizing: border-box;" class="_135editor"><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="color: #3E3E3E; font-size: 12px; letter-spacing: 0.4px; box-sizing: border-box;">[1]&nbsp;威廉·贝克、拉尔夫·马丁和卡尔·托尼，《房角石圣经注释丛书第十五卷：哥林多前后书》，崔晓雄译（香港：恩道出版社，2018），198－203。</span><br style="box-sizing: border-box;"/>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="font-size: 12px; color: #3E3E3E; box-sizing: border-box;">[2]&nbsp;贝克、马丁和托尼，《房角石圣经注释丛书第十五卷：哥林多前后书》，194。</span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><span style="font-size: 12px; color: #3E3E3E; box-sizing: border-box;">[3]&nbsp;同上。</span>
		</p></section><section style="padding: 0px 12px; letter-spacing: 0.4px; line-height: 1.8; font-size: 16px; box-sizing: border-box;" class="_135editor"><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p></section></section>

          
          <!-- 内容结束 -->
        </div>
      </div>
    </div>
  </div>
  <?php include "../footer.html" ?>
</body>

</html>