<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="zh-CN" lang="zh-CN" >
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="房角石圣经注释丛书">
  <meta name="keywords" content="房角石圣经注释丛书">
  <title>基于真理应对教会的问题-哥林多前书-房角石圣经注释丛书</title>
  <link rel="shortcut icon" href="../assets/img/favicon.png">
  <link rel="stylesheet" href="../assets/css/styles.css">

</head>
<body>
  <div class="content-wrapper">
    <?php include "../header.html" ?>
    <div class="container">
      <div class="row py-16">
        <div class="col-xl-6 col-md-10 col-lg-6 order-xl-2 mx-auto">
          <!-- 内容开始 -->

   <section style="font-size: 15px; color: rgb(0, 0, 0); letter-spacing: 0.4px; line-height: 1.8; padding-right: 12px; box-sizing: border-box;   text-align: justify;"><section style="margin: 10px 0px; text-align: left; justify-content: flex-start; display: flex; flex-flow: row nowrap; position: static; box-sizing: border-box;" class="_135editor"><section style="box-sizing:border-box;display: inline-block; vertical-align: bottom; width: auto; min-width: 10%; max-width: 100%; flex: 0 0 auto; height: auto; align-self: flex-end; margin: 0px -20px 0px 0px;"><section style="text-align: center; margin: 0px; position: static; box-sizing: border-box;"><section class="group-empty" style="box-sizing:border-box;display: inline-block; width: 47px; height: 47px; vertical-align: top; overflow: hidden; border-width: 0px; border-radius: 77px; border-style: solid; border-color: rgb(62, 62, 62); background-image: linear-gradient(to top, rgb(255, 243, 173) 0%, rgba(255, 243, 173, 0) 100%);"><svg viewbox="0 0 1 1" style="box-sizing:border-box;float:left;line-height:0;width:0;vertical-align:top;"></svg></section></section></section><section style="box-sizing:border-box;display: inline-block; vertical-align: bottom; width: auto; min-width: 10%; max-width: 100%; flex: 0 0 auto; height: auto; align-self: flex-end;"><section style="text-align: center; box-sizing: border-box;"><p style="margin: 0px; padding: 0px; box-sizing: border-box;"><strong style="box-sizing: border-box;">书 &nbsp; 卷 &nbsp; 导 &nbsp; 读 ✦</strong>
				</p></section><section style="margin: 0px; position: static; box-sizing: border-box;"><section style="font-size: 13px; text-align: justify; box-sizing: border-box;"><p style="text-align:left;  margin: 0px; padding: 0px; box-sizing: border-box;"><span style="background-color: #3E3E3E; color: #FFFFFF; box-sizing: border-box;">Books Introduction</span>
					</p></section></section></section></section><section style="text-align: center; font-size: 24px; color: rgb(0, 0, 0); box-sizing: border-box;" class="_135editor"><p style="margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p><p style="margin: 0px; padding: 0px; box-sizing: border-box;"><strong style="box-sizing: border-box;">基于真理应对教会的问题</strong>
		</p><p style="margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p></section><section style="text-align: center; justify-content: center; display: flex; flex-flow: row nowrap; margin: 10px 0px; position: static; box-sizing: border-box;transform: translate3d(9px, 0px, 0px);-webkit-transform: translate3d(9px, 0px, 0px);-moz-transform: translate3d(9px, 0px, 0px);-o-transform: translate3d(9px, 0px, 0px);" class="_135editor"><section style="box-sizing:border-box;display: inline-block; vertical-align: bottom; width: 105px; align-self: flex-end; flex: 0 0 auto; height: auto;"><section style="text-align: left; justify-content: flex-start; display: flex; flex-flow: row nowrap; position: static; box-sizing: border-box;"><section style="box-sizing:border-box;max-width: 100% !important;display: inline-block; width: 100%; vertical-align: top; align-self: flex-start; flex: 0 0 auto; background-color: rgb(248, 208, 95); border-width: 0px; border-radius: 405%; border-style: none; border-color: rgb(62, 62, 62); overflow: hidden; height: auto; box-shadow: rgb(255, 255, 255) -25px 0px 27px inset;"><section style="text-align: justify; box-sizing: border-box;"><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
						</p></section><section style="text-align: center; position: static; box-sizing: border-box;"><section style="text-align: justify; box-sizing: border-box;"><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
							</p></section></section><section style="text-align: justify; box-sizing: border-box;"><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
						</p></section></section></section></section><section style="box-sizing:border-box;display: inline-block; vertical-align: middle; width: 52%; flex: 0 0 auto; height: auto; align-self: center;"><section style="margin-top: 10px; margin-bottom: 10px; line-height: 0; position: static; box-sizing: border-box;transform: translate3d(-56px, 0px, 0px);-webkit-transform: translate3d(-56px, 0px, 0px);-moz-transform: translate3d(-56px, 0px, 0px);-o-transform: translate3d(-56px, 0px, 0px);"><section style="box-sizing:border-box;max-width: 100%; vertical-align: middle; display: inline-block; line-height: 0; width: 80%; height: auto;"><img class="raw-image" style="box-sizing:border-box;vertical-align: middle; width: 100%;" _width="100%" src="https://ehome.endao.co/book_image/detail/1670333812207.jpg" draggable="false" _src="https://ehome.endao.co/book_image/detail/1670333812207.jpg"/>
				</section></section><section style="text-align: left; margin: 0px 0px 10px; position: static; box-sizing: border-box;transform: translate3d(-56px, 0px, 0px);-webkit-transform: translate3d(-56px, 0px, 0px);-moz-transform: translate3d(-56px, 0px, 0px);-o-transform: translate3d(-56px, 0px, 0px);"><section style="box-sizing: border-box;"><p style="margin: 0px; padding: 0px; box-sizing: border-box;"><span style="letter-spacing: 0.4px; box-sizing: border-box;">房角石圣经注释丛书</span><strong style="box-sizing: border-box;"><br style="box-sizing: border-box;"/></strong>
					</p><p style="margin: 0px; padding: 0px; box-sizing: border-box;"><strong style="box-sizing: border-box;"><span style="letter-spacing: 0.4px; box-sizing: border-box;">第十五卷：哥林多前书</span></strong>
					</p></section></section></section></section><section style="font-size: 16px; color: rgb(0, 0, 0); letter-spacing: 0.4px; line-height: 1.9; padding: 0px 12px; box-sizing: border-box;" class="_135editor"><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;">初代教会时期的哥林多，实为一座繁华之城，融合了来自各地的居民、文化、娱乐、商业，还有世人崇拜的众多神明。诞生于此的哥林多教会，“年轻、困惑，在自己的文化中随波逐流，又受到其中不成熟成员的挑战，有太多的东西需要向其属灵的父亲学习”<span style="color: #FFCA00; box-sizing: border-box;">[1]</span>。因此，<span style="color: #3E3E3E; box-sizing: border-box;">哥林多前书所描述的这个教会，离我们很多人</span><span style="color: #FF8124; box-sizing: border-box;">并不遥远。</span>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;">威廉·贝克所著的<span style="color: #FF8124; box-sizing: border-box;">《房角石注释：哥林多前书》</span>，将整卷书的内容概括为“如何在一个不欢迎福音的气氛中活出福音，以及与此相关的具体问题”<span style="color: #FFCA00; box-sizing: border-box;">[2]</span>。显然，保罗需要处理具体问题。不过，正如贝克所言，保罗的处理方式是基于基督教信仰的神学，以神学作为讨论的前提与回应的背景。只是保罗大多时候并未直接表述这些神学教义。</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;">因此，读者的重要责任之一，是从保罗陈述的这些案例中总结出信仰的基本原则。<span style="color: #3E3E3E; box-sizing: border-box;">贝克的解经，在这方面为读者</span><span style="color: #FF8124; box-sizing: border-box;">提供了充分的信息和引导。</span>他不仅详细解释了书信中的用词和句法，而且在必要之处，补充了当时的文化与哲学背景，帮助今天的读者理解书信所陈述问题的实质。贝克也采用今天读者更容易理解的方式，总结了保罗的神学辩论思路与立场。如果我们希望从哥林多前书中找到信仰原则，从而学习如何回应今天教会中出现的种种问题，这本解经书将提供非常扎实的帮助。</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"/>
		</p></section><section style="margin: 0px 0%; text-align: left; justify-content: flex-start; display: flex; flex-flow: row nowrap; position: static; box-sizing: border-box;" class="_135editor"><section style="box-sizing:border-box;max-width: 100% !important;display: inline-block; width: 100%; vertical-align: top; padding: 20px; align-self: flex-start; flex: 0 0 auto; background-image: linear-gradient(to top, rgb(255, 243, 173) 0%, rgba(255, 243, 173, 0) 100%);"><section style="text-align: center; margin: 0px 0% 20px; line-height: 0; position: static; box-sizing: border-box;"><section style="box-sizing:border-box;max-width: 100%; vertical-align: middle; display: inline-block; line-height: 0; width: 60%; height: auto;"><img class="raw-image" style="box-sizing:border-box;vertical-align: middle; width: 100%;" _width="100%" src="https://ehome.endao.co/book_image/detail/1669887987892.png" draggable="false" _src="https://img.xiumi.us/xmi/ua/3O1Ws/i/06486484a6d3c53eb584ac03bbe449d9-sz_1979970.png"/>
				</section></section><section style="color: rgb(0, 0, 0); text-align: justify; font-size: 16px; letter-spacing: 0.4px; line-height: 1.9; padding: 0px 12px; box-sizing: border-box;"><p style="text-align:center;  margin: 0px; padding: 0px; box-sizing: border-box;"><strong style="box-sizing: border-box;">✦ &nbsp;房角石</strong><strong style="letter-spacing: 0.4px; box-sizing: border-box;">圣经注释丛书&nbsp; ✦</strong>
				</p><p style="text-align:center;  margin: 0px; padding: 0px; box-sizing: border-box;"><strong style="box-sizing: border-box;"><span style="background-color: #FFCA00; color: #FFFFFF; box-sizing: border-box;">全套34册 | 简体/繁體</span></strong>
				</p><p style="text-align:center;  margin: 0px; padding: 0px; box-sizing: border-box;"><span style="text-decoration: none; color: #000000; box-sizing: border-box;">人人都能读的高品质释经书</span>
				</p><p style="text-align:center;  margin: 0px; padding: 0px; box-sizing: border-box;"><a href="https://cbcs.endao.co/" target="_blank" style="color: rgb(255, 129, 36); box-sizing: border-box;" _href="https://cbcs.endao.co/"><span style="color: #FF8124; box-sizing: border-box;">点击了解更多→&nbsp;cbcs.endao.co</span></a>
				</p></section></section></section><p style=" margin: 0px; padding: 0px; box-sizing: border-box;" class="_135editor"><br style="box-sizing: border-box;"/>
	</p><section style="display: flex; flex-flow: row nowrap; margin: 10px 0%; text-align: center; justify-content: center; position: static; box-sizing: border-box;" class="_135editor"><section style="box-sizing:border-box;display: inline-block; vertical-align: middle; width: auto; flex: 0 0 0%; align-self: center; height: auto; margin: 0px; padding: 0px; box-shadow: rgb(0, 0, 0) 0px 0px 0px;"><section style="display: flex; flex-flow: row nowrap; justify-content: center; margin: -1px 0% 5px; position: static; box-sizing: border-box;"><section style="box-sizing:border-box;display: inline-block; vertical-align: bottom; width: auto; align-self: flex-end; flex: 0 0 0%; line-height: 0; letter-spacing: 0px; height: auto;"><section style="margin: 8px 0% -5px; position: static; box-sizing: border-box;transform: translate3d(1px, 0px, 0px);-webkit-transform: translate3d(1px, 0px, 0px);-moz-transform: translate3d(1px, 0px, 0px);-o-transform: translate3d(1px, 0px, 0px);"><section class="group-empty" style="box-sizing:border-box;display: inline-block; width: 6px; height: 6px; vertical-align: top; overflow: hidden; border-style: solid; border-width: 1px; border-radius: 50px 0px 50px 50px; border-color: rgb(255, 197, 41);"><svg viewbox="0 0 1 1" style="box-sizing:border-box;float:left;line-height:0;width:0;vertical-align:top;"></svg></section></section></section><section class="group-empty" style="box-sizing:border-box;display: inline-block; vertical-align: top; width: 22px; flex: 0 0 auto; align-self: stretch; height: auto; border-style: none none solid solid; border-width: 1px;  border-color: rgb(62, 62, 62) rgb(62, 62, 62) rgb(255, 197, 41) rgb(255, 197, 41);"><svg viewbox="0 0 1 1" style="box-sizing:border-box;float:left;line-height:0;width:0;vertical-align:top;"></svg></section></section></section><section style="box-sizing:border-box;display: inline-block; vertical-align: middle; width: auto; align-self: center; flex: 100 100 0%;"><section style="margin: 2px 0% 0px; position: static; box-sizing: border-box;"><section style="background-color: rgb(255, 197, 41); height: 1px; box-sizing: border-box;"><svg viewbox="0 0 1 1" style="box-sizing:border-box;float:left;line-height:0;width:0;vertical-align:top;"></svg></section></section></section></section><section style="padding: 0px 12px; font-size: 12px; color: rgb(62, 62, 62); box-sizing: border-box;" class="_135editor"><p style=" margin: 0px; padding: 0px; box-sizing: border-box;">[1] 威廉·贝克，《房角石圣经注释丛书第十五卷：哥林多前书》，崔晓雄译（香港：恩道出版社，2021），28。</p><p style=" margin: 0px; padding: 0px; box-sizing: border-box;">[2] 贝克，《房角石圣经注释丛书第十五卷：哥林多前书》，39。</p></section></section>       

          
          <!-- 内容结束 -->
        </div>
      </div>
    </div>
  </div>
  <?php include "../footer.html" ?>
</body>

</html>